### ISSUE TITLE
dump to s3

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/datapackage-pipelines-aws#1]
as a pipeline user, I want to be able to process data and save them on s3

## Acceptance criteria

* able to save files on s3 

## Tasks

* [x] go throught the okfn/measure codebase and understand how the work 
* [x] write tests 
* [x] write function to put files on s3
* [x] provide README

### Spec

```yaml

my-cool-pipeline:
  title: Cool data
  pipeline:
    -
      run: to_s3
      parameters:
        bucket: mybucket.name
        path: my/s3/path/{owner}/{name}/{version}
```
Note:  it should be possible to pass path exactly in this format as well. The script should be able to get the owner name, package name and the version from datapackage.json and add DataPackage to that path. Eg: executing the pipeline above should put files on `my.bucket.name/my/s3/path/core/finance-vix/lates/...`

* Version defaults to _latest_
* If path includes {owner}, it should present in datapackage.json as well Eg: 
```
{"name": "finance-vix", "owner": "core"}
```
